name: FactionEvent
version: '${project.version}'
main: fr.blixow.factionevent.FactionEvent
authors: [ SYNATIKS ,blixow14 ]
description: plugin d'event faction
commands:
  planning:
    description: Affiche le planning des events de la semaine.
  planningadd:
    usage: /planningadd
    description: Planification des events.
  planningremove:
    usage: /planningremove
    description: Suppression d'un event du planning.
  koth:
    usage: /koth
    description: Gestion des koths.
  kothlist:
    usage: /kothlist
    description: Affiche la liste des koths
  totem:
    usage: /totem
    description: Gestion des totems.
  totemlist:
    usage: /totemlist
    description: Affiche la liste des totems
  event:
    usage: /event
    description: Permet de gérer les attributs des événements
    aliases: [events, cevent, cevents]
  classement:
    usage: /classement
    description: Affiche le classement des factions
    aliases: [ftop, rankings, ranking]
  dtc:
    usage: /dtc
    description: Gestion des dtc
    aliases: [cdtc]
  dtclist:
    usage: /dtclist
    description: Affiche la liste des dtc
  lms:
    usage: /lms
    description: Gestion des lms
    aliases: [lastmanstanding]
  lmslist:
    usage: /lmslist
    description: Affiche la liste des lms